"""
Structured Pydantic Schemas and Data Models for ReviewRadar.
Defines schemas for classical diagnostics, statistical evidence, product sentiment,
and forensic fraud verdicts.
"""

from enum import Enum
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field, field_validator


class FraudClassification(str, Enum):
    GENUINE = "GENUINE"
    MACHINE_GENERATED_BOT = "MACHINE_GENERATED_BOT"
    INCENTIVIZED_SPAM = "INCENTIVIZED_SPAM"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SentimentType(str, Enum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    MIXED = "MIXED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class StatisticalEvidenceItem(BaseModel):
    """A single piece of statistical evidence citing classical NLP metrics."""
    metric_name: str = Field(description="Name of the cited statistical metric, e.g. 'Modifier-to-Content Ratio'.")
    observed_value: str = Field(description="The measured value in this review.")
    baseline_range: str = Field(description="Expected baseline range for organic human reviews.")
    interpretation: str = Field(description="Linguistic and forensic meaning of the discrepancy.")


class ProductSentiment(BaseModel):
    """Extracted genuine product sentiment and functionality aspects."""
    sentiment: SentimentType = Field(default=SentimentType.NEUTRAL, description="Overall sentiment expressed.")
    sentiment_score: float = Field(default=0.0, ge=-1.0, le=1.0, description="Polarity score from -1.0 to 1.0.")
    key_features_mentioned: List[str] = Field(default_factory=list, description="Specific product features cited.")
    is_genuine_feedback: bool = Field(default=True, description="Whether sentiment represents actual product usage.")


class FraudVerdict(BaseModel):
    """Authoritative forensic report delivered by the Expert Fraud Analyst."""
    classification: FraudClassification = Field(description="Final classification verdict.")
    confidence_score: float = Field(ge=0.0, le=1.0, description="Confidence score from 0.0 to 1.0.")
    fraud_risk_level: RiskLevel = Field(description="Operational moderation queue risk level.")
    linguistic_explanation: str = Field(description="In-depth forensic rationale linking classical stats to verdict.")
    statistical_evidence: List[StatisticalEvidenceItem] = Field(default_factory=list, description="Citations of metrics.")
    product_sentiment: ProductSentiment = Field(default_factory=ProductSentiment)
    anomaly_flags: List[str] = Field(default_factory=list, description="Consolidated anomaly flags.")

    @field_validator("confidence_score")
    @classmethod
    def clamp_confidence(cls, v: float) -> float:
        return max(0.0, min(1.0, round(v, 3)))


class ClassicalDiagnostics(BaseModel):
    """Consolidated statistical and syntactic footprint generated by classical NLP engine."""
    raw_text: str
    normalized_text: str
    tokens: List[str] = Field(default_factory=list)
    sentences: List[str] = Field(default_factory=list)
    token_count: int = 0
    sentence_count: int = 0
    
    # Normalizer metrics
    elongations_fixed: int = 0
    excessive_punct_fixed: int = 0
    leetspeak_fixed: int = 0
    uppercase_ratio: float = 0.0
    is_shout_case: bool = False
    
    # POS metrics
    modifier_count: int = 0
    content_count: int = 0
    modifier_to_content_ratio: float = 0.0
    superlative_density: float = 0.0
    noun_density: float = 0.0
    verb_density: float = 0.0
    type_token_ratio: float = 0.0
    hapax_ratio: float = 0.0
    pos_tag_frequencies: Dict[str, int] = Field(default_factory=dict)
    
    # N-Gram Perplexity metrics
    bigram_perplexity_laplace: float = 0.0
    bigram_perplexity_good_turing: float = 0.0
    sentence_perplexities: List[float] = Field(default_factory=list)
    perplexity_variance: float = 0.0
    oov_rate: float = 0.0
    
    # Flags
    classical_anomaly_flags: List[str] = Field(default_factory=list)


class ReviewRadarReport(BaseModel):
    """Complete end-to-end audit report combining classical diagnostics and LLM verdict."""
    review_id: str
    timestamp: str
    diagnostics: ClassicalDiagnostics
    verdict: FraudVerdict
    processing_time_ms: float = 0.0
